FROM registry.gitlab.com/crempp/node-example

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json .
COPY package-lock.json .

ENV NODE_ENV dev

RUN npm install

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "npm", "run", "test-ci" ]
